add_newline = false

scan_timeout = 10

prompt_order = [
    "username",
    "hostname",
    "kubernetes",
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "docker_context",
    "package",
    "golang",
    "java",
    "nodejs",
    "python",
    "rust",
    "terraform",
    "memory_usage",
    "aws",
    "cmd_duration",
    "custom",
    "line_break",
    "character",
]

[username]
disabled = false
show_always = true
